// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/verses-lobby/ChannelGuide.tsx": () => import("../components/mockups/verses-lobby/ChannelGuide.tsx"),
  "./components/mockups/verses-lobby/LiveFeed.tsx": () => import("../components/mockups/verses-lobby/LiveFeed.tsx"),
  "./components/mockups/verses-lobby/StationDial.tsx": () => import("../components/mockups/verses-lobby/StationDial.tsx")
};
